/**
 * POST /api/attendance/offline/session
 *
 * Creates or updates a ConductedSession with mwv1 crypto fields.
 * The session key is generated by the lecturer app and may be included
 * in the request body (sessionKey + sessionNonce). If omitted, the session
 * is created without a key and the lecturer app must sync it later via
 * POST /api/attendance/conducted-sessions/sync.
 *
 * Auth: Lecturer JWT (cookie or Authorization header).
 *       Admins may also create sessions by providing lecturerId in body.
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyLecturerAccessToken } from "@/lib/lecturerAuthJwt";
import { verifyAdminAuthToken } from "@/lib/adminAuthJwt";
import { generateSessionNonce } from "@/lib/attendanceCrypto";

export const runtime = "nodejs";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

export function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: cors });
}

export async function POST(req: NextRequest) {
  // ── Auth ────────────────────────────────────────────────────────────────
  let rawToken = req.cookies.get("lecturer_auth_token")?.value;
  if (!rawToken) {
    const ah = req.headers.get("authorization");
    if (ah?.startsWith("Bearer ")) rawToken = ah.slice(7).trim();
  }
  if (!rawToken) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401, headers: cors });
  }

  let lecturerId: string;
  try {
    ({ lecturerId } = verifyLecturerAccessToken(rawToken));
  } catch {
    // Accept admin tokens — they must supply lecturerId in body
    const adminPayload = verifyAdminAuthToken(rawToken);
    if (!adminPayload) {
      return NextResponse.json({ error: "Invalid or expired token." }, { status: 401, headers: cors });
    }
    lecturerId = ""; // filled from body below
  }

  // ── Parse body ──────────────────────────────────────────────────────────
  let body: {
    unitCode?: string;
    roomId?: string;          // Room UUID (preferred)
    roomCode?: string;        // fallback
    lectureRoom?: string;     // fallback display name
    lessonType?: string;
    sessionStart?: number;    // Unix seconds
    sessionDuration?: number; // seconds, default 3600
    lecturerId?: string;      // only accepted from admin callers
    sessionKey?: string;      // 64-char hex; generated by lecturer app
    sessionNonce?: number;    // uint32; generated by lecturer app
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400, headers: cors });
  }

  // Admin callers may override lecturerId
  if (!lecturerId) {
    if (!body.lecturerId) {
      return NextResponse.json({ error: "lecturerId is required for admin callers." }, { status: 400, headers: cors });
    }
    lecturerId = body.lecturerId;
  }

  if (!body.unitCode) {
    return NextResponse.json({ error: "unitCode is required." }, { status: 400, headers: cors });
  }
  if (!body.sessionStart) {
    return NextResponse.json({ error: "sessionStart (Unix seconds) is required." }, { status: 400, headers: cors });
  }

  const unitCodeNorm = body.unitCode.toUpperCase().replace(/\s+/g, "").replace(/[^A-Z0-9]/g, "");
  const sessionDuration = Math.max(60, Math.min(body.sessionDuration ?? 3600, 86400));
  const sessionStartSecs = body.sessionStart;
  const sessionStartDate = new Date(sessionStartSecs * 1000);
  const lessonType = body.lessonType ?? "LEC";

  // ── Resolve numeric BLE IDs ─────────────────────────────────────────────
  const unit = await prisma.unit.findFirst({
    where: {
      OR: [
        { code: body.unitCode },
        { code: unitCodeNorm },
      ],
    },
    select: { id: true, code: true, bleId: true },
  });
  if (!unit) {
    return NextResponse.json({ error: `Unit '${body.unitCode}' not found.` }, { status: 404, headers: cors });
  }

  let roomName: string | null = null;
  let bleRoomId: number | null = null;

  if (body.roomId) {
    const room = await prisma.room.findUnique({
      where: { id: body.roomId },
      select: { name: true, roomCode: true, bleId: true },
    });
    if (room) {
      roomName = room.roomCode || room.name;
      bleRoomId = room.bleId ?? null;
    }
  } else if (body.roomCode) {
    const room = await prisma.room.findFirst({
      where: { roomCode: body.roomCode },
      select: { name: true, roomCode: true, bleId: true },
    });
    if (room) {
      roomName = room.roomCode || room.name;
      bleRoomId = room.bleId ?? null;
    }
  }

  const lectureRoom = (body.lectureRoom ?? roomName ?? body.roomCode ?? "").toUpperCase().replace(/\s+/g, "");
  if (!lectureRoom) {
    return NextResponse.json({ error: "roomId, roomCode, or lectureRoom is required." }, { status: 400, headers: cors });
  }

  // ── Validate optional session key from lecturer app ─────────────────────
  // Accept both lowercase and uppercase hex — normalise to lowercase for storage.
  const incomingKey   = (typeof body.sessionKey === "string" && /^[0-9a-fA-F]{64}$/.test(body.sessionKey))
    ? body.sessionKey.toLowerCase() : null;
  const incomingNonce = (typeof body.sessionNonce === "number" && Number.isFinite(body.sessionNonce))
    ? Math.floor(body.sessionNonce) : null;

  // Fall back to server-generated nonce only when lecturer didn't send one
  const sessionNonce = incomingNonce ?? generateSessionNonce();

  // ── Create ConductedSession ─────────────────────────────────────────────
  const existing = await prisma.conductedSession.findFirst({
    where: {
      unitCode:     unitCodeNorm,
      lectureRoom,
      sessionStart: sessionStartDate,
    },
    select: { id: true, sessionKey: true },
  });
  const hadKey = !!existing?.sessionKey;

  const session = await prisma.conductedSession.upsert({
    where: {
      unitCode_lectureRoom_sessionStart: {
        unitCode: unitCodeNorm,
        lectureRoom,
        sessionStart: sessionStartDate,
      },
    },
    update: {
      sessionNonce:    BigInt(sessionNonce),
      sessionDuration,
      bleUnitId:       unit.bleId ?? null,
      bleRoomId:       bleRoomId ?? null,
      lessonType,
      lecturerId,
      // Only store key if incoming non-null and nothing stored yet (COALESCE)
      ...(!hadKey && incomingKey ? { sessionKey: incomingKey } : {}),
    },
    create: {
      unitCode:        unitCodeNorm,
      lectureRoom,
      lessonType,
      sessionStart:    sessionStartDate,
      lecturerId,
      sessionNonce:    BigInt(sessionNonce),
      sessionDuration,
      bleUnitId:       unit.bleId ?? null,
      bleRoomId:       bleRoomId ?? null,
      sessionKey:      incomingKey ?? null,
    },
    select: {
      id: true, unitCode: true, lectureRoom: true, lessonType: true,
      sessionStart: true, sessionDuration: true, sessionNonce: true,
      sessionKey: true, bleUnitId: true, bleRoomId: true,
    },
  });

  return NextResponse.json(
    {
      sessionId:       session.id,
      sessionNonce:    Number(session.sessionNonce),
      sessionStart:    sessionStartSecs,
      sessionDuration: session.sessionDuration,
      unitId:          session.bleUnitId ?? null,
      roomId:          session.bleRoomId ?? null,
      unitCode:        session.unitCode,
      lectureRoom:     session.lectureRoom,
      lessonType:      session.lessonType,
    },
    { status: 201, headers: cors },
  );
}
