/**
 * MarkWise attendance cryptography — mwv1 rawPayload verification.
 *
 * The session key is generated by the lecturer app and synced to the backend
 * via POST /api/attendance/conducted-sessions/sync. It is stored in the
 * ConductedSession record and used here for verification. It is NEVER sent
 * to student-authenticated endpoints.
 *
 * Supported rawPayload formats:
 *   MWQR0x01:{base64}                       QR code  (MWQR1: accepted as legacy compat)
 *   MANUAL:{6-digit-pin}:{absoluteCounter}  Manual PIN
 *   MWBLE:v1:{nonce16}:{counter}:{uid}:{rid} BLE beacon
 */
import crypto from "crypto";

export const runtime = "nodejs";

export type VerificationStatus =
  | "pending"
  | "verified"
  | "rejected"
  | "legacy_unverifiable";

export interface AttendanceSession {
  sessionKey: string;       // 64-char hex stored in conducted_sessions
  sessionNonce: number;     // uint32 CSPRNG
  sessionStart: number;     // Unix epoch seconds
  sessionDuration: number;  // seconds
  bleUnitId: number | null; // Unit.bleId — needed for BLE/QR payload validation
  bleRoomId: number | null; // Room.bleId
}

export interface VerifyResult {
  status: VerificationStatus;
  reason: string | null;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function hmacHex(keyHex: string, message: string): string {
  return crypto
    .createHmac("sha256", Buffer.from(keyHex, "hex"))
    .update(message, "utf8")
    .digest("hex");
}

/** Canonical payload string per spec: "mwv1|unitId|roomId|start|duration|nonce" */
function encodePayload(session: AttendanceSession): string {
  return (
    `mwv1|${session.bleUnitId ?? 0}|${session.bleRoomId ?? 0}|` +
    `${session.sessionStart}|${session.sessionDuration}|${session.sessionNonce}`
  );
}

/** PIN derivation: first 4 bytes of HMAC token as uint32, mod 10^6 */
function tokenToPin(token: string): string {
  const n = (parseInt(token.slice(0, 8), 16)) >>> 0;
  return String(n % 1_000_000).padStart(6, "0");
}

// ─── Per-format verifiers ─────────────────────────────────────────────────────

function verifyQr(
  rawPayload: string,
  session: AttendanceSession,
  scannedAtSec: number,
): VerifyResult {
  // "MWQR0x01:" is 9 chars (current); "MWQR2:" is 6 chars (legacy compat)
  const prefixLen = rawPayload.startsWith("MWQR0x01:") ? 9 : 6;
  let content: string;
  try {
    content = Buffer.from(rawPayload.slice(prefixLen), "base64").toString("utf8");
  } catch {
    return { status: "rejected", reason: "bad_base64" };
  }

  // Split from the right: last 64 chars = token, then counter, then encodedPayload
  const lastPipe = content.lastIndexOf("|");
  const receivedToken = content.slice(lastPipe + 1);
  if (receivedToken.length !== 64) {
    return { status: "rejected", reason: "bad_token_length" };
  }

  const rest = content.slice(0, lastPipe);
  const counterPipe = rest.lastIndexOf("|");
  const receivedCounter = parseInt(rest.slice(counterPipe + 1), 10);
  const encodedPayload = rest.slice(0, counterPipe);

  const parts = encodedPayload.split("|");
  if (parts.length !== 6 || parts[0] !== "mwv1") {
    return { status: "rejected", reason: "bad_payload_format" };
  }

  const payloadNonce = parseInt(parts[5]!, 10);
  if ((payloadNonce >>> 0) !== (session.sessionNonce >>> 0)) {
    return { status: "rejected", reason: "nonce_mismatch" };
  }

  const expectedToken = hmacHex(session.sessionKey, `${encodedPayload}|${receivedCounter}`);
  if (receivedToken !== expectedToken) {
    return { status: "rejected", reason: "hmac_invalid" };
  }

  // Counter drift tolerance: ±5 QR windows (3 s each = ±15 s)
  const expectedCounter = Math.max(0, Math.floor((scannedAtSec - session.sessionStart) / 3));
  if (Math.abs(receivedCounter - expectedCounter) > 5) {
    return { status: "rejected", reason: "counter_drift" };
  }

  return { status: "verified", reason: null };
}

function verifyPin(
  rawPayload: string,
  session: AttendanceSession,
): VerifyResult {
  // Format: MANUAL:{6-digit-pin}:{absoluteCounter}
  const parts = rawPayload.split(":");
  if (parts.length !== 3) {
    return { status: "rejected", reason: "bad_format" };
  }

  const submittedPin = parts[1]!;
  const absoluteCounter = parseInt(parts[2]!, 10);

  if (!/^\d{6}$/.test(submittedPin)) {
    return { status: "rejected", reason: "bad_pin_format" };
  }
  if (isNaN(absoluteCounter)) {
    return { status: "rejected", reason: "bad_counter" };
  }

  // Convert absolute counter → session-relative counter
  // absoluteCounter = floor(submissionTime_sec / 30)
  const relativeCounter = absoluteCounter - Math.floor(session.sessionStart / 30);
  if (relativeCounter < 0) {
    return { status: "rejected", reason: "counter_before_session" };
  }

  const encoded = encodePayload(session);

  // Accept exact window plus ±1 adjacent for boundary clock skew
  for (const delta of [0, -1, 1]) {
    const adj = relativeCounter + delta;
    if (adj < 0) continue;
    const token = hmacHex(session.sessionKey, `${encoded}|${adj}`);
    if (tokenToPin(token) === submittedPin) {
      return { status: "verified", reason: null };
    }
  }

  return { status: "rejected", reason: "pin_mismatch" };
}

function verifyBle(
  rawPayload: string,
  session: AttendanceSession,
  scannedAtSec: number,
): VerifyResult {
  // Format: MWBLE:v1:{nonce16}:{counter}:{unitId}:{roomId}
  const inner = rawPayload.slice(9); // strip "MWBLE:v1:"
  const parts = inner.split(":");
  if (parts.length !== 4) {
    return { status: "rejected", reason: "bad_format" };
  }

  const [nonce16Str, counterStr, unitIdStr, roomIdStr] = parts;
  const receivedNonce16 = parseInt(nonce16Str!, 10);
  const receivedCounter = parseInt(counterStr!, 10);
  const receivedUnitId  = parseInt(unitIdStr!, 10);
  const receivedRoomId  = parseInt(roomIdStr!, 10);

  if ([receivedNonce16, receivedCounter, receivedUnitId, receivedRoomId].some(isNaN)) {
    return { status: "rejected", reason: "bad_format" };
  }

  // BLE only carries the lower 16 bits of the nonce (packet size constraint)
  if ((session.sessionNonce & 0xFFFF) !== (receivedNonce16 & 0xFFFF)) {
    return { status: "rejected", reason: "nonce_mismatch" };
  }
  if (session.bleUnitId !== null && receivedUnitId !== session.bleUnitId) {
    return { status: "rejected", reason: "unit_mismatch" };
  }
  if (session.bleRoomId !== null && receivedRoomId !== session.bleRoomId) {
    return { status: "rejected", reason: "room_mismatch" };
  }

  // Counter drift: ±7 windows (21 s) — enough for BLE relay chains
  // (worst-case 8-hop relay adds ~1.2 s; ±7 gives 20 s headroom vs ±5 for QR).
  const expectedCounter = Math.max(0, Math.floor((scannedAtSec - session.sessionStart) / 3));
  if (Math.abs(receivedCounter - expectedCounter) > 7) {
    return { status: "rejected", reason: "counter_drift" };
  }

  // Time window: session ±30 s grace
  const sessionEnd = session.sessionStart + session.sessionDuration;
  if (scannedAtSec < session.sessionStart - 30 || scannedAtSec > sessionEnd + 30) {
    return { status: "rejected", reason: "outside_session_window" };
  }

  return { status: "verified", reason: null };
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Verify a rawPayload string against the session's stored key.
 * Handles all three current formats and gracefully classifies legacy ones.
 */
export function verifyRawPayload(
  rawPayload: string | null | undefined,
  session: AttendanceSession,
  scannedAtSec: number,
): VerifyResult {
  if (!rawPayload) {
    return { status: "legacy_unverifiable", reason: "missing_payload" };
  }
  if (rawPayload.startsWith("MWQR1:")) {
    // Log potential downgrade attempts — legitimate clients upgraded long ago.
    console.warn("[attendanceCrypto] legacy MWQR1 payload rejected — possible downgrade attempt");
    return { status: "rejected", reason: "legacy_qr_format_rejected" };
  }
  // "MWQR0x01:" is the current prefix; "MWQR2:" is accepted for backward compat
  if (rawPayload.startsWith("MWQR0x01:") || rawPayload.startsWith("MWQR2:")) {
    return verifyQr(rawPayload, session, scannedAtSec);
  }
  if (rawPayload.startsWith("MANUAL:")) {
    const parts = rawPayload.split(":");
    // New format has 3 parts: MANUAL:{pin}:{absoluteCounter}
    // Old 2-part format (MANUAL:{pin}) has no absoluteCounter — treat as legacy
    if (parts.length === 3) return verifyPin(rawPayload, session);
    return { status: "legacy_unverifiable", reason: "old_manual_format" };
  }
  if (rawPayload.startsWith("MWBLE:v1:")) {
    return verifyBle(rawPayload, session, scannedAtSec);
  }
  // JSON blob or other pre-upgrade format
  return { status: "legacy_unverifiable", reason: "unknown_format" };
}

/** Generate a cryptographically random uint32 session nonce */
export function generateSessionNonce(): number {
  return crypto.randomBytes(4).readUInt32BE(0);
}
